OPENCV_VERSION="4.6.0"
export LIBRARY_PATH="$HOME/opt/opencv${OPENCV_VERSION}/lib:$LIBRARY_PATH"
export LD_LIBRARY_PATH=$HOME"/opt/opencv${OPENCV_VERSION}/lib:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH=$HOME"/opt/opencv${OPENCV_VERSION}/lib/pkgconfig:$PKG_CONFIG_PATH"
